<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxwhxwe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxwhxwe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxwhxwe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxwhxwe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxwhxwe\appProdProjectContainer(array(
    'container.build_hash' => 'Xxwhxwe',
    'container.build_id' => '08b43dc0',
    'container.build_time' => 1540476532,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxwhxwe');
