<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVg4osza\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVg4osza/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVg4osza.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVg4osza\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVg4osza\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vg4osza',
    'container.build_id' => '9cbf2ccc',
    'container.build_time' => 1540480378,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVg4osza');
